void setup() {
 pinMode(2,OUTPUT);
 pinMode(3,OUTPUT);
 pinMode(4,OUTPUT);
 digitalWrite(2,LOW);
 digitalWrite(3,LOW);
 digitalWrite(4,LOW);
}

void loop() {

 //L1
 pinMode(2,OUTPUT);
 digitalWrite(2,HIGH);  
 pinMode(3,OUTPUT);
 digitalWrite(3,LOW);  
 pinMode(4,INPUT);
 digitalWrite(4,LOW);   
 delay(500);
 digitalWrite(2,LOW);
 digitalWrite(3,LOW);
 pinMode(4,OUTPUT); 
 digitalWrite(4,LOW);
 delay(500);
 //L2
 digitalWrite(2,LOW);  
 digitalWrite(3,HIGH);  
 pinMode(4,INPUT);
 digitalWrite(4,LOW);   
 delay(500);
 digitalWrite(2,LOW);
 digitalWrite(3,LOW);
 digitalWrite(4,LOW);
 delay(500);
 //L3
  pinMode(2,INPUT);
 digitalWrite(2,HIGH);  
 pinMode(3,OUTPUT);
 digitalWrite(3,HIGH);  
 pinMode(4,OUTPUT);
 digitalWrite(4,LOW);   
 delay(500);
 digitalWrite(2,LOW);
 digitalWrite(3,LOW);
 digitalWrite(4,LOW);
 delay(500);
 //L4
 pinMode(2,INPUT);
 digitalWrite(2,LOW);  
 pinMode(3,OUTPUT);
 digitalWrite(3,LOW);  
 pinMode(4,OUTPUT);
 digitalWrite(4,HIGH);   
 delay(500);
 digitalWrite(2,LOW);
 digitalWrite(3,LOW);
 digitalWrite(4,LOW);
 delay(500);
 //L5
 pinMode(2,OUTPUT);
 digitalWrite(2,HIGH);  
 pinMode(3,INPUT);
 digitalWrite(3,LOW);  
 pinMode(4,OUTPUT);
 digitalWrite(4,LOW);   
 delay(500);
 digitalWrite(2,LOW);
 digitalWrite(3,LOW);
 digitalWrite(4,LOW);
 delay(500); 
  //L6
 pinMode(2,OUTPUT);
 digitalWrite(2,LOW);  
 pinMode(3,INPUT);
 digitalWrite(3,LOW);  
 pinMode(4,OUTPUT);
 digitalWrite(4,HIGH);   
 delay(500);
 digitalWrite(2,LOW);
 digitalWrite(3,LOW);
 digitalWrite(4,LOW);
 delay(500);
}
